<html>
	<head>
		<title>제목변경2</title>
	</head>
    <body>
    <header>
        <h1>git</h1>
    </header>
	<ul>
		<li>Git이란?</li>
		<li>버전이란?</li>
		<li>Branch?</li>
		<li>브랜치란?</li>
		<li>충돌</li>
		<li>원격저장소</li>
	</ul>
        <dl>
            <dt>테스트</dt><dd>실험을 여러번 해볼 것.</dd>
        </dl>
    </body>
</html>